---
- include: transfer-ca-docker.yml
- hosts: tsuru
  become: true
  handlers:
    - include: roles/guilhermeoki.docker/handlers/main.yml
  tasks: 
  - name: Ensure CA key is present
    file:
      path: "{{ DOCKER_SSL_DIR }}/ca-key.pem"
      state: file

  - name: Ensure CA is present
    file: 
      path: "{{ DOCKER_SSL_DIR }}/ca.pem"
      state: file

  - name: Generate TLS Server Key for Docker Daemon
    command: openssl genrsa -out server-key.pem 4096
    args: 
      chdir: "{{ DOCKER_SSL_DIR }}"

  - name: Generate TLS Server Certificate Signing request for Docker Daemon
    command: openssl req -subj "/CN=$HOSTNAME" -sha256 -new -key server-key.pem -out server.csr
    args: 
      chdir: "{{ DOCKER_SSL_DIR }}"

  - name: Generate TLS Server Config Files for Docker Daemon
    lineinfile: 
      dest: "{{ DOCKER_SSL_DIR }}/extfile.cnf"
      line: "subjectAltName = IP:{{ ansible_default_ipv4.address }},IP:127.0.0.1"
      state: present
      create: yes

  - name: Generate TLS Server Certificate for Docker Daemon
    command: openssl x509 -req -days 365 -sha256 -in server.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out server-cert.pem -extfile extfile.cnf -passin pass:{{ CA_PASSWD }}
    args:
      chdir: "{{ DOCKER_SSL_DIR }}"

  - name: Change directory permissions to read Docker certificates.
    file:
      path: "{{ DOCKER_SSL_DIR }}"
      mode: 0744
      state: directory
      recurse: yes

  - name: Ensure docker daemon config is present
    copy:
      src: docker
      dest: /etc/sysconfig/docker
    notify:
      - reload unit
      - restart docker

  - meta: flush_handlers

  - name: ensure starts on system boot
    service:
      name: docker
      enabled: yes
