---
- hosts: tsuru-api
  tasks:
  - name: create volume group for docker
    lvg:
      vg: vg.services
      pvs: /dev/xvdf
      pesize: 32  
  - name: create lv thinpool data
    lvol:
      vg: vg.services
      size: 90%VG
      lv: thinpool
  - name: create lv thinpool meta
    lvol:
      vg: vg.services
      size: 5%VG
      lv: thinpoolmeta
  - name: prepare pool
    command: "{{ item }}"
    with_items:
      - lvconvert -y --zero n -c 512K --thinpool vg.services/thinpool --poolmetadata vg.services/thinpoolmeta
      - mkdir -p /etc/lvm/profile
  - name: configure thinpool profile
    copy:
      src: profile
      dest: /etc/lvm/profile
  - name: verify thinpool
    shell: lvs -o+seg_monitor
# it is needs make profile lvm configuration
