---
- name: install Docker engine
  package:
    name={{ item }}
    state=present
  with_items:
    - "{{ docker_package }}-{{ docker_version }}"
    - cloud-utils-growpart

- name: install Docker systemd service
  template:
    src: docker.service.j2
    dest: /etc/systemd/system/docker.service
    mode: "0644"
  notify:
    - reload systemd
    - restart docker

- name: copy Docker configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  with_items:
    - src: docker.j2
      dest: /etc/sysconfig/docker
    - src: docker-network.j2
      dest: /etc/sysconfig/docker-network
    - src: docker-storage-setup.j2
      dest: /etc/sysconfig/docker-storage-setup
    - src: daemon.json.j2
      dest: /etc/docker/daemon.json
  notify: restart docker
