---
- name: install Docker engine
  package:
    name={{ item }}
    state=present
  with_items:
    - "{{ docker_package }}-{{ docker_version }}"
    - cloud-utils-growpart

- name: install Docker systemd service
  template:
    src: "{{ docker_package }}.service.j2"
    dest: /etc/systemd/system/{{ docker_package}}.service
    mode: "0644"
  notify:
    - reload systemd
    - restart docker

- name: copy Docker configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  with_items:
    - src: docker.j2
      dest: /etc/sysconfig/{{ docker_package }}
    - src: docker-network.j2
      dest: /etc/sysconfig/{{ docker_package }}-network
    - src: docker-storage-setup.j2
      dest: /etc/sysconfig/{{ docker_package }}-storage-setup
    - src: daemon.json.j2
      dest: /etc/{{ docker_package }}/daemon.json
  notify: restart docker
