- name: determine if LVM is configured for docker
  shell: ls /etc/docker.lvmconfig
  ignore_errors: true
  changed_when: false
  register: lvmset

- include: lvm.yml
  when: lvmset|failed
  static: no

- include: tls.yml
  when: docker_tls
  static: no

- include: daemon.yml

