---
- name: configure TLS structure for Docker
  include: tls.yml
  when: docker_tls
  static: no

- name: install and configure docker engine
  include: engine.yml

- meta: flush_handlers

- name: ensure Docker is up and running
  service:
    name: docker
    state: started
    enabled: yes
