---
- name: install and configure docker engine
  include: engine.yml

- name: configure TLS structure for Docker
  include: tls.yml
  when: docker_tls.enabled
  static: no

- meta: flush_handlers

- name: ensure Docker is up and running
  service:
    name: docker
    state: started
    enabled: yes

- name: ensure Docker storage is correctly working
  shell: systemctl status docker-storage-setup \
    | grep "(code=exited, status=0/SUCCESS)"
  changed_when: false
