---
- name: ensure certs.d folder exists
  file:
    path: "/etc/docker/certs.d"
    state: directory

- name: write TLS files
  template:
    src: "{{ item.name }}.j2"
    dest: "/etc/docker/certs.d/{{ item.name }}"
    mode: "{{ item.mode }}"
  with_items:
    - name: ca.crt
      mode: 0644
    - name: engine.cert
      mode: 0644
    - name: engine.key
      mode: 0600
